### ISSUE TITLE
Failed to start immich-pod.service: Unit immich-pod.service not found.

### ISSUE THREAD

**Issue by jasonblewis** [jbtrystram/immich-podman-systemd#5]
I just tried this but the line to start the immich-pod service doesn't fined the .service

```
root@snow:~/source/immich-podman-systemd# systemctl --user -M immich@.host start immich-pod.service
Failed to start immich-pod.service: Unit immich-pod.service not found.
```

does the immich-pod.service get auto generated?

**Comment by jbtrystram** [comment]
Yes ! The service files are auto generated by quadlet.
`systemctl daemon-reload` will run the generator. 

Systemd generators run very early at boot, so there is no logs unfortunately.

You can test your files running `/usr/libexec/podman/quadlet -dryrun`

**Comment by jasonblewis** [comment]
for clarity, I was trying to run this as a rootless podman. 

I am running on debian stable which only had podman v4.3.1. I suspect it doesn't have the quadlet program.

**Comment by jbtrystram** [comment]
support for `.pod` was added in 4.9 so yeah, that's a issue
