### ISSUE TITLE
Problem on Fedora Silverblue 40

### ISSUE THREAD

**Issue by Froggy232** [jbtrystram/immich-podman-systemd#7]
Hi,
First, thanks for your work!
I try to launch immich on a podman rootless config, but fail to launch `immich-microservices.service`
It tell me that a dependency job failed, even though all other contenair are deployed and operational, expect immich.server of course.
But immich-database tell me : UTC [162] FATAL:  role "root" does not exist
Maybe this is related?
Anyway, thanks for your help, and of course feel free to ask for any other informations you would need.
Best regards

**Comment by jbtrystram** [comment]
I've had the same issue and haven't found a propper fix yet. 
Does manually restarting immich-server.service once the others are up helps ? 
If so you can try to add `ExecStartPre=sleep 30` in a [Service] section in immich-server.container to see if that helps. It definitely does for me.

Let me know if that helps

**Comment by Froggy232** [comment]
Hi,
Unfortunally, no, it still doesn't work.
Thanks for your help anyway, it's nice from you.
Have a nice day!

**Comment by jbtrystram** [comment]
did you update the image to 1.106 ? I think the microservices container was dropped, i need to update this repo accordingly. I am travelling right now so i won't have time to do it until next week unfortunately.

**Comment by jbtrystram** [comment]
Hey 
did you manage to run it ? If so, what was the issue ?

**Comment by jbtrystram** [comment]
Okay so I ran into the same issue while updating today. 
Some of the quadlet files needed updating. I cannot get the database healtcheck to work so I had to disable it. I'll push an update

**Comment by Froggy232** [comment]
Hi,
Sorry for the delay, I will wait for your update so!
Thanks you

**Comment by jbtrystram** [comment]
I updated the main branch with the changes needed for 1.108. Let me know how that goes

**Comment by jbtrystram** [comment]
Since I haven't heard back i am closing this. Feel free to reopen if you have issues
